=== GuDzpoz/TreeSvgTest/document.dtd
<!ELEMENT document (title, node*)>
<!ELEMENT node (title, referrers, references, node*)>
<!ATTLIST node id CDATA #REQUIRED>
<!ATTLIST node file CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT referrers (path*)>
<!ELEMENT references (path*)>
<!ELEMENT see (path*)>
<!ELEMENT seen (path*)>
<!ELEMENT path (#PCDATA)>
<!ATTLIST path id CDATA #IMPLIED>

=== GuDzpoz/TreeSvgTest/test.xml
<!DOCTYPE document SYSTEM "document.dtd">
<document title="test">
  <node id="Science" file="NaN">
    <title>Science</title>
    <referrers>
      <path>/Science</path>
    </referrers>
    <references>
      <path>/Science</path>
    </references>
    <see></see>
    <seen></seen>
    <node id="Math" file="NaN">
        <title>Math</title>
        <referrers></referrers>
        <references></references>
        <see></see>
        <seen></seen>
    </node>
  </node>
</document>
